# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./examples-benthos
    binary: benthos-app

dockers:
  - id: benthos-app-x86_64
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    skip_push: false
    image_templates:
      - "core.brumby-dragon.ts.net/library/benthos-wal:{{ .Tag }}-amd64"
  - id: benthos-app-arm64
    goos: linux
    goarch: arm64
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    image_templates:
      - "core.brumby-dragon.ts.net/library/benthos-wal:{{ .Tag }}-arm64"

docker_manifests:
  - name_template: "core.brumby-dragon.ts.net/library/benthos-wal:{{ .Tag }}"

    image_templates:
      - "core.brumby-dragon.ts.net/library/benthos-wal:{{ .Tag }}-amd64"
      - "core.brumby-dragon.ts.net/library/benthos-wal:{{ .Tag }}-arm64"

#archives:
#  - format: tar.gz
#    # this name template makes the OS and Arch compatible with the results of `uname`.
#    name_template: >-
#      {{ .ProjectName }}_
#      {{- title .Os }}_
#      {{- if eq .Arch "amd64" }}x86_64
#      {{- else if eq .Arch "386" }}i386
#      {{- else }}{{ .Arch }}{{ end }}
#      {{- if .Arm }}v{{ .Arm }}{{ end }}
#    # use zip for windows archives
#    format_overrides:
#      - goos: windows
#        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"