apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"acid.zalan.do/v1","kind":"postgresql","metadata":{"annotations":{},"creationTimestamp":"2024-10-04T21:58:57Z","generation":10,"labels":{"team":"acid"},"name":"best-cluster","namespace":"default","resourceVersion":"889543","uid":"6e36ab6c-af39-4d73-a219-9819136745f0"},"spec":{"allowedSourceRanges":[],"enableConnectionPooler":true,"enableLogicalBackup":true,"enableMasterLoadBalancer":true,"enableMasterPoolerLoadBalancer":true,"enableReplicaLoadBalancer":true,"maintenanceWindows":[],"numberOfInstances":2,"postgresql":{"version":"16"},"preparedDatabases":{"devices":{"defaultUsers":true,"extensions":{"pgcrypto":"public","wal2json":"public"},"schemas":{"public":{"defaultRoles":true,"defaultUsers":true}}}},"resources":{"limits":{"cpu":"500m","memory":"500Mi"},"requests":{"cpu":"100m","memory":"100Mi"}},"teamId":"acid","users":{"app_test":[],"john":["superuser"]},"volume":{"iops":3000,"size":"10Gi","throughput":125}},"status":{"PostgresClusterStatus":"Running"}}
  creationTimestamp: "2024-10-04T21:58:57Z"
  generation: 11
  labels:
    team: acid
  name: best-cluster
  namespace: default
  resourceVersion: "1042529"
  uid: 6e36ab6c-af39-4d73-a219-9819136745f0
spec:
  allowedSourceRanges: []
  enableConnectionPooler: true
  enableLogicalBackup: true
  enableMasterLoadBalancer: true
  enableMasterPoolerLoadBalancer: true
  enableReplicaLoadBalancer: true
  maintenanceWindows: []
  numberOfInstances: 2
  sidecars:
    - name: postgres-exporter
      image: quay.io/prometheuscommunity/postgres-exporter:latest
      ports:
        - name: metrics
          containerPort: 9187
      env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@localhost:5432/postgres?sslmode=disable"
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
  postgresql:
    version: "16"
  preparedDatabases:
    devices:
      defaultUsers: true
      extensions:
        pgcrypto: public
        wal2json: public
      schemas:
        public:
          defaultRoles: true
          defaultUsers: true
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    app_test: []
    john:
    - superuser
  volume:
    iops: 3000
    size: 10Gi
    throughput: 125
status:
  PostgresClusterStatus: Running
